"""Add missing columns

Revision ID: 770e9e6ce165
Revises: 
Create Date: 2026-04-14 22:31:29.651430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770e9e6ce165'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable
    op.add_column('shops', sa.Column('location', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('working_hours', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('speed_factor', sa.Float(), nullable=True))
    
    # 2. Update existing rows with defaults
    op.execute("UPDATE shops SET location = 'Campus' WHERE location IS NULL")
    op.execute("UPDATE shops SET working_hours = '9AM - 6PM' WHERE working_hours IS NULL")
    op.execute("UPDATE shops SET approval_status = 'approved' WHERE approval_status IS NULL")
    op.execute("UPDATE shops SET speed_factor = 1.0 WHERE speed_factor IS NULL")
    
    # 3. Alter columns to NOT NULL
    op.alter_column('shops', 'location', nullable=False)
    op.alter_column('shops', 'working_hours', nullable=False)
    op.alter_column('shops', 'approval_status', nullable=False)
    op.alter_column('shops', 'speed_factor', nullable=False)
    op.add_column('shops', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shops', 'users', ['owner_id'], ['user_id'])
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'owner_id')
    op.drop_column('shops', 'speed_factor')
    op.drop_column('shops', 'rejection_reason')
    op.drop_column('shops', 'approval_status')
    op.drop_column('shops', 'working_hours')
    op.drop_column('shops', 'location')
    # ### end Alembic commands ###
